name: "PR to Main"
on:
  pull_request:
    branches:
      - main

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: version-check
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo ${{ steps.version-check.outputs.version-did-change }}
      - name: Fail on no version updated
        if: ${{ steps.version-check.outputs.version-did-change == 'false' }}
        run: 'echo "No version change :/" && exit 1'
  
  auto-approve-pr:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'dkershner6'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
